#Parameters for left drive
joint_name: left_wheel_joint
EncIncrPerRevMot: 8000
VelMeasFrqHz: 1
GearRatio: 6
BeltRatio: 1
Sign: -1.0
VelMaxEncIncrS: 240000
AccIncrS: 80000
DecIncrS: 80000
Homing: false
HomePos: 0
HomeVel: 10000
HomeEvent: 9
HomeDigIn: 0x0001
HomeTimeOut: 1000
VelPModeEncIncrS: 10
CANId: 1

#TODO: dang something is not right with the returned value of the wheelencoders OR the kinematics OR the gear ratio OR.... (echo /odom)
quickFix: -1
