port: /dev/ttyUSB0
baud: 500000
inverted: true
frame_id: /laserback_link
scan_id: 7
#start_scan: -5550
start_scan: 0
#stop_scan: 5541
stop_scan: 541
scan_intervals: [[-1.66, 1.66]]
translation: [-0.394, 0.0, 0.0]
orientation: [0.0, 0.0, 1.5708]
scan_duration: 0.025
scan_cycle_time: 0.04
