global_costmap:
  # Coordinate frame and tf parameters
  global_frame: map         # Test with /map as per documentation
  robot_base_frame: base_link
  transform_tolerance: 1.5  # Specifies the delay in transform (tf) data that is tolerable in seconds.
                            # This parameter serves as a safeguard to losing a link in the tf tree while
                            # still allowing an amount of latency the user is comfortable with to exist
                            # in the system. For example, a transform being 0.2 seconds out-of-date may
                            # be tolerable, but a transform being 8 seconds out of date is not. If the
                            # tf transform between the coordinate frames specified by the global_frame
                            # and robot_base_frame parameters is transform_tolerance seconds older than
                            # ros::Time::now(), then the navigation stack will stop the robot. Default: 0.2
  # Rate parameters
  update_frequency: 0.5     # The frequency in Hz for the map to be updated. Default 5.0
  # publish_frequency: 1.0    # The frequency in Hz for the map to be publish display information. Default: 0.0

  static_map: true

  # Inflation layer
  # cost_scaling_factor: 10.0 # Default: 10.0
  inflation_radius: 1.5     # A high inflation radius in the global costmap helps the robot go more
                            # in the middle of areas, instead of going very close to objects and walls.
                            # The robot can still go through narrow areas, just at a higher cost, so it
                            # may find a longer and more open route.