#Parameters for right drive
joint_name: right_wheel_joint
EncIncrPerRevMot: 4096
VelMeasFrqHz: 1
GearRatio: 15
BeltRatio: 1
Sign: -1.0
VelMaxEncIncrS: 129706
AccIncrS: 65190
DecIncrS: 65190
Homing: false
HomePos: 0
HomeVel: 10000
HomeEvent: 9
HomeDigIn: 0x0001
HomeTimeOut: 10
VelPModeEncIncrS: 10
CANId: 2

#TODO: dang something is not right with the returned value of the wheelencoders OR the kinematics OR the gear ratio OR.... (echo /odom)
quickFix: -1

